<a href="https://colab.research.google.com/github/alevchencko/-2-8-/blob/main/%D0%9B%D0%B0%D0%B1_4_%D0%9B%D0%B5%D0%B2%D1%87%D0%B5%D0%BD%D0%BA%D0%BE_(%D1%87%D0%BC).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# Визначаємо матриці A та B
A = np.array([
    [1, 1, 1],
    [0, 1, 1],
    [0, 0, 1]
])
B = np.array([
    [7, 5, 3],
    [0, 7, 5],
    [0, 0, 7]
])
# Обчислюємо матриці AB і BA
AB = np.dot(A, B)
BA = np.dot(B, A)
# Обчислюємо матрицю C = AB - BA
C = AB - BA
# Виводимо результати
print("Матриця AB:")
print(AB)
print("\nМатриця BA:")
print(BA)
print("\nМатриця C = AB - BA:")
print(C)


Матриця AB:
[[ 7 12 15]
 [ 0  7 12]
 [ 0  0  7]]

Матриця BA:
[[ 7 12 15]
 [ 0  7 12]
 [ 0  0  7]]

Матриця C = AB - BA:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [2]:
import numpy as np
# Визначаємо матрицю
A = np.array([
    [-1, 0, 2],
    [0, 1, 0],
    [1, 2, -1]
])
# Підносимо матрицю A до степеня 2
A_squared = np.dot(A, A)
# Виводимо результат
print("Матриця A^2:")
print(A_squared)


Матриця A^2:
[[ 3  4 -4]
 [ 0  1  0]
 [-2  0  3]]


In [3]:
import numpy as np
# Визначаємо матриці
A = np.array([
    [3, 5],
    [6, -1]
])
B = np.array([
    [2, 1],
    [-3, 2]
])
# Обчислюємо добуток матриць A і B
C = np.dot(A, B)
# Виводимо результат
print("Добуток матриць A і B:")
print(C)


Добуток матриць A і B:
[[-9 13]
 [15  4]]


In [4]:
import numpy as np
# Визначаємо матрицю
A = np.array([
    [2, 4, 5],
    [1, 1, 2],
    [2, 4, 3]
])
# Обчислюємо визначник матриці A
det_A = np.linalg.det(A)
# Виводимо результат
print("Визначник матриці A:")
print(det_A)

Визначник матриці A:
4.0


In [5]:
import numpy as np
# Визначаємо матрицю
A = np.array([
    [2, 3, 4, 1],
    [1, 2, 3, 4],
    [3, 4, 1, 2],
    [4, 1, 2, 3]
])
# Обчислюємо визначник матриці A
det_A = np.linalg.det(A)
# Виводимо результат
print("Визначник матриці A:")
print(det_A)

Визначник матриці A:
-160.00000000000009


In [6]:
import numpy as np
# Визначаємо матрицю
A = np.array([
    [1, 1, 1, 1],
    [1, 1, -1, -1],
    [1, -1, 1, -1],
    [1, -1, -1, 1]
])
# Перевіримо, чи матриця є невиродженою (чи існує обернена матриця)
det_A = np.linalg.det(A)
if det_A != 0:
    # Обчислюємо обернену матрицю
    A_inv = np.linalg.inv(A)
    print("Обернена матриця A:")
    print(A_inv)
else:
    print("Матриця є виродженою, обернена матриця не існує.")

Обернена матриця A:
[[ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25 -0.25 -0.25]
 [ 0.25 -0.25  0.25 -0.25]
 [ 0.25 -0.25 -0.25  0.25]]


In [8]:
import numpy as np
# Визначаємо матрицю
A = np.array([
    [1, -1, 3, 4],
    [0, -1, 2, 1],
    [1, 1, -1, 2],
    [2, 3, -5, 3]
])
# Обчислюємо ранг матриці A
rank_A = np.linalg.matrix_rank(A)
# Виводимо результат
print("Ранг матриці A:")
print(rank_A)

Ранг матриці A:
3


In [9]:
import numpy as np
# Визначаємо матрицю A та вектор b
A = np.array([
    [3, 2, 1],
    [2, -1, 1],
    [1, 5, 0]
])
b = np.array([5, 6, -3])
# Метод Крамера
det_A = np.linalg.det(A)
# A_x, A_y, A_z - матриці для заміни стовпців
A_x = np.array([
    [5, 2, 1],
    [6, -1, 1],
    [-3, 5, 0]
])

A_y = np.array([
    [3, 5, 1],
    [2, 6, 1],
    [1, -3, 0]
])

A_z = np.array([
    [3, 2, 5],
    [2, -1, 6],
    [1, 5, -3]
])
det_Ax = np.linalg.det(A_x)
det_Ay = np.linalg.det(A_y)
det_Az = np.linalg.det(A_z)
x_Cramer = det_Ax / det_A
y_Cramer = det_Ay / det_A
z_Cramer = det_Az / det_A
print("Метод Крамера: x =", x_Cramer, ", y =", y_Cramer, ", z =", z_Cramer)
# Матричний метод
A_inv = np.linalg.inv(A)
x_matrix = np.dot(A_inv, b)
print("Матричний метод: x =", x_matrix[0], ", y =", x_matrix[1], ", z =", x_matrix[2])
# Метод Гауса (використовуємо numpy.linalg.solve)
x_Gauss = np.linalg.solve(A, b)
print("Метод Гауса: x =", x_Gauss[0], ", y =", x_Gauss[1], ", z =", x_Gauss[2])
# Перевірка за допомогою numpy.linalg.solve
x_check = np.linalg.solve(A, b)
print("Перевірка за допомогою solve(): x =", x_check[0], ", y =", x_check[1], ", z =", x_check[2])

Метод Крамера: x = 1.9999999999999956 , y = -0.9999999999999998 , z = 1.0000000000000073
Матричний метод: x = 2.0000000000000013 , y = -1.0000000000000004 , z = 1.0000000000000022
Метод Гауса: x = 1.9999999999999982 , y = -0.9999999999999996 , z = 1.0000000000000042
Перевірка за допомогою solve(): x = 1.9999999999999982 , y = -0.9999999999999996 , z = 1.0000000000000042


In [10]:
import numpy as np
# Встановлюємо розміри матриці
N = 4  # Кількість рядків
M = 5  # Кількість стовпців
# Створюємо матрицю з випадкових чисел
A = np.random.randint(0, 10, size=(N, M))
# Виводимо матрицю
print("Матриця A:")
print(A)
# Обчислюємо середнє значення для кожного рядка
row_means = np.mean(A, axis=1)
# Знаходимо найменше серед середніх значень рядків
min_row_mean = np.min(row_means)
# Виводимо результати
print("\nСередні значення для кожного рядка:")
print(row_means)
print("\nНайменше серед середніх значень рядків:")
print(min_row_mean)

Матриця A:
[[3 3 3 5 7]
 [3 1 8 2 3]
 [8 0 1 1 0]
 [5 9 8 6 8]]

Середні значення для кожного рядка:
[4.2 3.4 2.  7.2]

Найменше серед середніх значень рядків:
2.0
